### ISSUE TITLE
Question: Deciding which plugin versions to use

### ISSUE THREAD

**Issue by alexbarbato** [vrabbi-tap/tdp-plugin-wrappers#1]
Hi there!

Appreciate you taking the time to wrap these.

Out of curiosity, how did you decide which versions of the plugins to wrap? 

As I'm going to write my own plugin and then continue on to potentially wrap the plugin, I'm curious what the workflow you worked out here looked like. I don't suppose I can just start with OSS Backstage and make a new plugin on latest because I'll likely have version clashes with TDP, but maybe you didn't notice that or found a way to work through it?

The TDP docs call out creating a new app in line with an older version of create-app 
```
npx @backstage/create-app@0.5.2 --skip-install
```
Which I'm guessing is why you looked for older versions of the plugins? or is that coincidence?

**Comment by vrabbi** [comment]
I always pulled the latest and wrapped them. If they didnt work i went back to an older one which i think i only had to do once or twice. Since i wrapped them nee versions have come out and i have not updated the plugins as im offlone working on a ci task to automate that but it will take time

**Comment by alexbarbato** [comment]
Ah cool, thanks!
